
run_name: &run_name auto_base_zero_20220926
max_length: &max_length 512

model:
  type: ibv2 intent classification slot filling
  size: base
  model_name_or_path: ai4bharat/IndicBERT-MLM-only
  pretrained_weights: /home/sumanth/massive/pretrained_models/ibv2-mlm-only.bin
  pretrained_weight_prepend: bert.
  strict_load_pretrained_weights: false
  model_config_args:
    attention_probs_dropout_prob: 0.35
    hidden_act: gelu
    hidden_dropout_prob: 0.25
    hidden_size: 768
    initializer_range: 0.02
    intermediate_size: 3072
    layer_norm_eps: 1e-05
    max_position_embeddings: 512
    num_attention_heads: 12
    num_hidden_layers: 12
    output_past: true
    pad_token_id: 1
    type_vocab_size: 2
    vocab_size: 250000
    use_crf: false
    slot_loss_coef: 2.0
    hidden_layer_for_class: 10
    head_num_layers: 2
    head_layer_dim: 8192
    head_intent_pooling: max
    freeze_layers: bert.embeddings.word_embeddings.weight

tokenizer:
  model_name_or_path: ai4bharat/IndicBERT-MLM-only
  tok_args:
    max_len: *max_length

collator:
  type: massive intent class slot fill
  args:
    max_length: *max_length
    padding: longest

train_val:
  train_dataset: /home/sumanth/massive/IN-MASSIVE/hf/IN-MASSIVE.train
  train_locales: en-US
  dev_dataset: /home/sumanth/massive/IN-MASSIVE/hf/IN-MASSIVE.dev
  intent_labels: /home/sumanth/massive/IN-MASSIVE/hf/IN-MASSIVE.intents
  slot_labels: /home/sumanth/massive/IN-MASSIVE/hf/IN-MASSIVE.slots
  slot_labels_ignore:
    - Other
  eval_metrics: all
  trainer_args:
    output_dir: /home/sumanth/massive/outputs/ibv2-mlm-only
    logging_dir: /home/sumanth/massive/outputs/ibv2-mlm-only
    save_strategy: steps
    save_steps: 500
    evaluation_strategy: steps
    eval_steps: 500
    save_total_limit: 5
    learning_rate: 1e-5
    lr_scheduler_type: constant_with_warmup
    warmup_steps: 500
    weight_decay: 0.1
    gradient_accumulation_steps: 4
    per_device_train_batch_size: 256
    per_device_eval_batch_size: 256
    num_train_epochs: 500
    remove_unused_columns: false
    label_names:
      - intent_num
      - slots_num
    logging_steps: 100
    log_level: info
    locale_eval_strategy: all and each
    disable_tqdm: false